### ISSUE TITLE
Dienstverleners en eIDAS

### ISSUE THREAD

**Issue by RonBeemster** [MinBZK/gdi-toegang#1]
minor dingetje maar in het model lijkt nu geen andere relatie tussen dienstverleners en eIDAS-koppelpunt mogelijk dan via TVS. Volgens mij zijn Eherkenningsmakelaars (of beter, de makelaars uit het eTD stelsel) ook zonder TVS in staat om authenticatieverzoeken naar het eIDAS koppelpunt te sturen. In hoeverre willen we in de huidige situatie compleet zijn?

**Comment by RonBeemster** [comment]
wellicht handig ter onderbouwing https://www.logius.nl/domeinen/toegang/eidas/documentatie/Nederland-bereidt-zich-voor-op-eIDAS

**Comment by dgreefhorst** [comment]
Je hebt gelijk, ik heb een relatie toegevoegd
